config_docker: &config_docker
  docker:
    - image: jspc/ci-worker:1.5.0
  resource_class: small

version: 2.1
jobs:
  test:
    <<: *config_docker
    steps:
      - checkout
      - run: make

  deploy:
    <<: *config_docker
    steps:
    - checkout
    - run: make
    - run: make deploy
    - run: make purge

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
          context: BUILD
          filters:
            tags:
              only: /.*/
      - deploy:
          context: BUILD
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
