name: Non-release build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build CVs
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make      
                 
      - uses: actions/upload-artifact@v2
        with:
          name: cv
          path: dist/
